version: '3.9'
services:
  techbox:
    image: artifycz/techbox:v1.4
    restart: always
    container_name: 'techbox'
    volumes:
      - ./data/world:/data/world
      - ./data/logs:/data/logs
      - ./data/crash-reports:/data/crash-reports
    ports:
      - 25565:25565
